meta_product_name: "Builder Helper"
meta_title: "Builder Helper - Helping builders with their projects everyday!"
meta_description: "Builder Helper is the leading App in home renovation
                   that enables anyone to build a list of tools and find them in the nearest store."
meta_image: "builderimage.jpg"